using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailArchiver.Migrations
{
    /// <inheritdoc />
    public partial class MigrateV2610_2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ============================================================
            // 1) Retention period of stored originals: 8 years
            // ============================================================
            // New originals are retained until the end of the 8th year after
            // the capture year (was: 10th). Rows that already exist keep their
            // RetainUntil; UPDATE stays forbidden on that table.
            //
            // In a hardened setup (doc/WormStorage.md) the application role
            // does not own archive_worm and cannot replace the function. The
            // administrator then runs doc/sql/MigrateV2610_2-archive_worm.sql
            // first; this block sees the new version and skips. If neither has
            // happened, the migration stops with a message instead of silently
            // keeping the old period.
            migrationBuilder.Sql(@"
                DO $$
                DECLARE
                    fn regprocedure := 'archive_worm.verify_source_insert()'::regprocedure;
                    may_replace boolean;
                BEGIN
                    IF pg_get_functiondef(fn) LIKE '%interval ''9 years''%' THEN
                        RETURN;
                    END IF;

                    SELECT r.rolsuper OR pg_has_role(current_user, p.proowner, 'USAGE')
                      INTO may_replace
                      FROM pg_proc p, pg_roles r
                     WHERE p.oid = fn AND r.rolname = current_user;

                    IF NOT may_replace THEN
                        RAISE EXCEPTION 'archive_worm is owned by another role. Run doc/sql/MigrateV2610_2-archive_worm.sql as database superuser, then start the application again.';
                    END IF;

                    EXECUTE $fn$
                        CREATE OR REPLACE FUNCTION archive_worm.verify_source_insert()
                        RETURNS TRIGGER AS $body$
                        DECLARE
                            actual_hash text;
                        BEGIN
                            actual_hash := encode(sha256(NEW.""RawMime""), 'hex');
                            IF NEW.""Sha256"" IS NULL OR lower(NEW.""Sha256"") <> actual_hash THEN
                                RAISE EXCEPTION 'Original message hash mismatch for email % (given %, actual %)',
                                    NEW.""ArchivedEmailId"", NEW.""Sha256"", actual_hash;
                            END IF;
                            NEW.""Sha256"" := actual_hash;
                            NEW.""Size"" := octet_length(NEW.""RawMime"");
                            NEW.""CapturedAt"" := now();
                            -- 8 years, counted from the end of the capture year
                            NEW.""RetainUntil"" := date_trunc('year', now()) + interval '9 years';
                            RETURN NEW;
                        END;
                        $body$ LANGUAGE plpgsql;
                    $fn$;

                    EXECUTE $c$
                        COMMENT ON COLUMN archive_worm.""ArchivedEmailSources"".""RetainUntil""
                            IS 'No deletion before this time; set by trigger on insert to the end of the 8th year after the capture year'
                    $c$;
                END $$;
            ");

            // ============================================================
            // 2) Pauses of the automatic deletion (e.g. during a tax audit)
            // ============================================================
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS mail_archiver.""RetentionHolds"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""StartedAt"" timestamp with time zone NOT NULL,
                    ""StartedBy"" character varying(255) NOT NULL,
                    ""Reason"" text NOT NULL,
                    ""EndedAt"" timestamp with time zone NULL,
                    ""EndedBy"" character varying(255) NULL
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // The retention function is not rolled back: shortening or lengthening
            // the period again is an administrator decision.
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS mail_archiver.""RetentionHolds"";");
        }
    }
}
